config/routes.rb
Rails.application.routes.draw do
 
 
  get 'page/about'

  get 'page/contact'
 
  post '/carts/edit/:id', to: 'carts#edit', as: 'edit_cart'
  delete 'sign_out', :to => 'devise/sessions#destroy'
 
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" , :registrations => 'users/registrations' }  
 
  resources :categories
  resources :products
  resources :pictures
  resource :cart, only: [:show]
  
  resources :order_items, only: [:create, :update, :destroy]
  
  

  root 'products#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
     namespace :admin do
      root :to => 'admin/users#index'    
       resources :users
     end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products , :dependent => :destroy


  def self.title_by_product_id (id)
    @category = Category.find(id).title
  end
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissabele">
      <button type="" class="close" data-dismiss="alert" ariahidden="true">&times;</button>
      <h4><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h4>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-goup">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit  class: "btn btn-primary" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category, class: "btn btn-link" %> |
<%= link_to 'Back', categories_path, class: "btn btn-link" %>

app/views/categories/index.html.erb
 <div class="row">
    <% @categories.each do |category| %>
      <div class="col-md-3">
	<div class="caption">
        <h3><%= category.title %></h3>
	<p><%= I18n.t 'actual'%> <%= pluralize(category.products.count," product") %></p>
        <%= link_to 'Show', category, class: "btn btn-link" %>
        <%= link_to 'Edit', edit_category_path(category), class: "btn btn-link" %>
        <%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %>
	</div>
	</div>
      

    <% end %>
  </div>

<br>

<%= link_to 'New Category', new_category_path, class: "btn btn-link"%>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>


<div class="row">
  <div class="col-md-6">
    <h3><%= @category.title %></h3>
  </div>
  <div class="col-md-6">
  <% unless @category.products.count < 1 %>
    <p><%= pluralize(@category.products.count, 'product') %></p>
     <% @category.products.each do |product| %>
   
     <div class="col-md-3 thumbnail">
      <%= image_tag product.pictures.first.image.url(:thumb) %>
      <p><%= product.title %></p>
    </div>
     
    <% end %>
    <% else %>
     <div class="col-md-3">
     <p class="notice"><%= I18n.t 'no products' %></p>
     </div>
     <% end %>
 </div>
</div>
</div>
<%= link_to 'Edit', edit_category_path(@category),class: "btn btn-link" %> |
<%= link_to 'Back', categories_path,class: "btn btn-link" %>