config/routes.rb
Rails.application.routes.draw do
 
 
  get 'page/about'

  get 'page/contact'
 
  post '/carts/edit/:id', to: 'carts#edit', as: 'edit_cart'
  delete 'sign_out', :to => 'devise/sessions#destroy'
 
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" , :registrations => 'users/registrations' }  
 
  resources :categories
  resources :products
  resources :pictures
  resource :cart, only: [:show]
  
  resources :order_items, only: [:create, :update, :destroy]
  
  

  root 'products#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
     namespace :admin do
      root :to => 'admin/users#index'    
       resources :users
     end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :products , :dependent => :destroy
  

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
	 :omniauthable, :omniauth_providers => [:google_oauth2]


  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(:email => data["email"]).first
    
     unless user
         user = User.create(
            email: data["email"],
            password: Devise.friendly_token[0,20],
	    provider: "google"
        )
     end
    user

  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
 before_filter :authenticate_user!, :admin_user?
# before_action :set_user , only: [:show , :edit, :update, :destroy]


  def index
    @users = User.all
    @orders = Order.all
    @order_items = OrderItem.all
  end

  # GET /admin/users/edit/1
  def edit
    @user  = User.find(params[:id])
    respond_to do |format|
      format.html 
      format.json { render json: @user }
    end
  end


  def update_resource(resource, params)
  end 

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update(user_params)
       	format.html { redirect_to :admin_users, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
  end
 end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


private
  def admin_user?
   redirect_to root_path, :alert => 'This page is allowed for admin' unless current_user.admin
  end

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name,:email,:admin)
    end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
      @user = User.from_omniauth(request.env["omniauth.auth"])
       session[:user_id] = @user.id
      if @user.persisted?
        flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
	sign_in_and_redirect @user, :event => :authentication
      else
        session["devise.google_data"] = request.env["omniauth.auth"]
	redirect_to new_user_registration_url
      end
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  def edit
    super
    @orders = Order.where(:user_id,current_user.id)
  end

  
  # PUT /resource
  # def update
  #   super
  # end


  def update_resource(resource, params)
    if current_user.provider == "google"
      params.delete("current_password")
      resource.update_without_password(params)
    else
      resource.update_with_password(params)
    end
  end

  

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  #     session[:user_id] = @user.id
  #      flash[:success]="Welcome, #{@user.email}!"
  # end 
   

  # POST /resource/sign_in
  # def create
  #   super
  #   session[:user_id] = @user.id
  #      flash[:success]="Welcome, #{@user.email}!"
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/admin/users/_form.html.erb
<%= form_for @user, url: admin_user_path(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissabele">
      <button type="" class="close" data-dismiss="alert" ariahidden="true">&times;</button>
      <h4><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h4>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :admin %>
    <%= f.check_box :admin, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit  class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<%= render 'form' %>


<%= link_to 'Back', admin_users_path, class: "btn btn-link" %>

app/views/admin/users/index.html.haml
%p= link_to "New User", new_admin_user_path,class: 'btn btn-primary btn-default'
.row
  %h4 Current Users:
  %table.table-bordered.table-striped.table-condensed
    %thead
      %tr
        %th Username
        %th Email
        %th signed in
        %th last sign in
        %th created at
        %th updated at
        %th provider
        %th role
        %th ---
    %tbody
      - @users.each do |user|
        %tr
          %td= user.name 
          %td= user.email 
          %td= user.sign_in_count 
          %td= user.last_sign_in_at
          %td= user.created_at 
          %td= user.updated_at
          %td= user.provider
          - if user.admin 
            %td administrator
          - else
            %td user
          %td= link_to 'Edit', edit_admin_user_path(user)


.row
  %h4 Current Orders:
  %table.table-bordered.table-striped.table-condensed
    %thead
      %tr
        %th Id
        %th Status
        %th Owner
        %th Items

    %tbody
      - @orders.each do |order|
        %tr
          %td= order.id
          %td #{OrderStatus.find(order.order_status_id).name}
          %td #{User.find(order.user_id).email}
          %td
            %ul
            - order.order_items.each do |item|
              %li #{item.id} #{Product.find(item.product_id).title}
 

.row
  %table.table-bordered.table-striped.table-condensed
    %thead
      %tr
        %th Id
        %th product id
        %th order id
    %tbody
      - @order_items.each do |item|
        %tr
          %td= item.id
          %td= item.product_id
          %td= item.order_id