config/routes.rb
Rails.application.routes.draw do
 
 
  get 'page/about'

  get 'page/contact'
 
  post '/carts/edit/:id', to: 'carts#edit', as: 'edit_cart'
  delete 'sign_out', :to => 'devise/sessions#destroy'
 
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" , :registrations => 'users/registrations' }  
 
  resources :categories
  resources :products
  resources :pictures
  resource :cart, only: [:show]
  
  resources :order_items, only: [:create, :update, :destroy]
  
  

  root 'products#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
     namespace :admin do
      root :to => 'admin/users#index'    
       resources :users
     end
end

app/models/product.rb
class Product < ActiveRecord::Base
 has_many :pictures, :dependent => :destroy
 has_many :order_items
 belongs_to :category
 belongs_to :user
 belongs_to :offer
 
 #default_scope { where(active: true) }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! , only: [:edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    if params[:category_id]
        @products = Category.find(params[:category_id]).products
    else
     	@products = Product.all
    end
    @order_item = current_order.order_items.new
   end


  # GET /products/1
  # GET /products/1.json
  def show
    @product  = Product.find(params[:id])
    @pictures = @product.pictures

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
    @product  = Product.find(params[:id])
    @pictures = @product.pictures
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)


    respond_to do |format|
      if @product.save
          if params[:images]
      	    #===== The magic is here ;)
            params[:images].each { |image|
            @product.pictures.create(image: image)
       	     }
      	     end

        format.html { redirect_to edit_user_registration_path , notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(product_params)
        if params[:images]
          # The magic is here ;)
          params[:images].each { |image|
            @product.pictures.create(image: image)
          }
        end

        format.html { redirect_to edit_user_registration_path, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to edit_user_registration_path, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :pictures,:category_id,
      					      :user_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for @product, :html => { :multipart => true } do |f| %>
<% if @product.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

    <ul>
	<% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
	<% end %>
    </ul>
</div>
<% end %>

<div class="field">
    <label for="product_category">Category</label><br/>
    <%= select "product","category_id",
	Category.all.collect { |c| [c.title,c.id]} %> <br />
</div>

<div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
</div>
<div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
</div>
<div class="control-group">
    <%= f.label :pictures, :class => 'control-label' %>
    <div class="controls">
        <%= file_field_tag "images[]", type: :file, multiple: true %>
    </div>
</div>
<%= f.hidden_field :user_id, :value => current_user.id %>
<div class="actions">
    <%= f.submit %>
</div>

<% end %>

app/views/products/_product_row.html.haml
.well    
  .row
    .col-md-4
      = link_to image_tag(product.pictures.first.image.url(:medium)), product_path(product)
    .col-md-8
      %h4= product.title 
      %p= product.description
      - if current_user && current_user.id != product.user_id && OrderItem.product_in_current_order(product.id,current_order.id) != true
        .col-md-4.col-md-offset-7{:id => "product-#{product.id}"}
          = form_for order_item, :remote => "true" do |f| 
            .input-group-btn
              = f.hidden_field :product_id, value: product.id
              = f.hidden_field :user_id, value: current_user.id
              = f.submit "Add to Cart", class: "btn btn-primary" 
      - if current_user && current_user.id == product.user_id
        .col-md-4.col-md-offset-7
        
          .input-group-btn{:id => "product-#{product.id}"}
            = button_to "Edit", edit_product_path(product),class: 'btn btn-primary btn-success',:method => :get
        
        
		

app/views/products/edit.html.erb
<%= render 'form' %>

<div class="row">
  <ul class="thumbnails files">
<% if @pictures  %>
  <% @pictures.each do |pic| %>
    <li class="span3" id="picture_<%= pic.id %>">
    <div class="thumbnail">
      <%= image_tag pic.image.url(:medium) %>
  
      <div class="caption">
        <p style="text-align: center;">
  <p style="text-align: center;">
                <%= link_to "Delete", pic,
                  :data => { :confirm => "Are you sure?" },
                  :method => :delete
                %>

        </p>
      </div>
    </div>
    </li>
  <% end %>
<% end %>
</ul>
</div>
<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.haml
.row
  .col-md-6
    = form_tag products_path, :method => 'get' do
      .input-group
      = select_tag "category_id", options_from_collection_for_select(Category.all, "id", "title"),:selected => "true",:onchange => 'this.form.submit();', class: 'form-control' 


.row
  .panel.panel-default
    .panel-body
      - @products.each do |product|
        = render "product_row",product: product, order_item: @order_item

app/views/products/new.html.erb
<h1>New Product</h1>

<% if current_user %>
<%= render 'form' %>
<% else %>
<p><%= link_to 'Log in' , new_user_session_path %> to create Products for your accaount</p>
<% end %>
<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class="row">

  <div class="col-md-4">

<% unless @pictures.empty? %>
  <% @pictures.each do |pic| %>
    <div  id="picture_<%= pic.id %>">

<%= image_tag pic.image.url(:medium) %>

 </div>


<% end %>
<% end %>  
</div>



<div class="col-md-8">
  <ul class="list-group">
<li class="list-group-item">
  <strong>Category:</strong>
  <%= @product.category.title %>
</li>


<li class="list-group-item">
  <strong>Title:</strong>
  <%= @product.title %>
</li>

<li class="list-group-item">
  <strong>Description:</strong>
  <%= @product.description %>
</li>

<li class="list-group-item">
  <strong>User:</strong>
  <%= @product.user.email %>
</li>

</ul>
</div>
</div>


<% if current_user && current_user.id == @user_id %>
<%= link_to 'Edit', edit_product_path(@product),class: 'btn btn-primary' %> |
<% end %>
<%= link_to 'Back', products_path,class: 'btn btn-primary' %>