config/routes.rb
Rails.application.routes.draw do
 
 
  get 'page/about'

  get 'page/contact'
 
  post '/carts/edit/:id', to: 'carts#edit', as: 'edit_cart'
  delete 'sign_out', :to => 'devise/sessions#destroy'
 
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" , :registrations => 'users/registrations' }  
 
  resources :categories
  resources :products
  resources :pictures
  resource :cart, only: [:show]
  
  resources :order_items, only: [:create, :update, :destroy]
  
  

  root 'products#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
     namespace :admin do
      root :to => 'admin/users#index'    
       resources :users
     end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products , :dependent => :destroy


  def self.title_by_product_id (id)
    @category = Category.find(id).title
  end
  
end

app/models/offer.rb
class Offer < ActiveRecord::Base
  belongs_to :users
  has_many :offer_items


end

app/models/offer_item.rb
class OfferItem < ActiveRecord::Base
  belongs_to :products
  belongs_to :orders
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :order_status
  has_many :order_items
  before_create :set_order_status


  private
  def set_order_status
    self.order_status_id = 1
  end
  
  
  
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order

  validate :product_present
  validate :order_present

  def self.product_in_current_order(product_id,current_order_id)
    @test = OrderItem.where(product_id: product_id,order_id: current_order_id)
    if @test != []
      @test = true
    else
      @test = nil
    end
    @test
  end
  
  private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  
  def order_present
    if order.nil?
      errors.add(:order,"is not a valid order")
    end
  end
  
end

app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
  has_many :orders
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :product
  has_attached_file :image, styles: { 
    		      	      	      medium: "300x300>", 
				      thumb: "100x100>" 
				      }
				      # default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  def self.picture_first_as_thumb (product_id)
   @picture = Picture.where(product_id: product_id)
   @picture_first = @picture.first
   @picture_first_as_thumb = @picture_first.image.url(:thumb)
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
 has_many :pictures, :dependent => :destroy
 has_many :order_items
 belongs_to :category
 belongs_to :user
 belongs_to :offer
 
 #default_scope { where(active: true) }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :products , :dependent => :destroy
  

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
	 :omniauthable, :omniauth_providers => [:google_oauth2]


  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(:email => data["email"]).first
    
     unless user
         user = User.create(
            email: data["email"],
            password: Devise.friendly_token[0,20],
	    provider: "google"
        )
     end
    user

  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user! , only: [:show,:edit]


  def show
    @order_items = current_order.order_items
    @offer_items = current_offer.offer_items
  end

  def edit
    @order = Order.find(params[:id])
    session[:order_id] = @order.id
    @offer = Offer.where(order_id:  @order.id).first
    session[:offer_id] = @offer.id
    @order_items = @order.order_items
  end
  
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/kontakt_helper.rb
module KontaktHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order.order_items.size} Items in Cart", cart_path, class: "btn btn-link" %>

app/views/layouts/_footer.html.erb
<p>Copyright 2016  --  Sascha Kohler</p>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">DEKOTAUSCH Inc. 2016</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li><%= link_to "About", page_about_path  %></li>
      <li><%= link_to "Contact", page_contact_path  %></li>
      </ul>
    <ul class="nav navbar-nav navbar-right">
	<li class="cart-text"> <%= render 'layouts/cart_text' %></li>
	<% if user_signed_in? %>
	<% if current_user.admin %>
	<li><%= link_to 'admin', admin_users_path %><li>
	    <% end %>
	<li><%= link_to current_user.email, edit_user_registration_path %><li>
	<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete  %></li>
	<% else %>
	<li><%= link_to 'Google+', user_google_oauth2_omniauth_authorize_path %></li>
	<li><%= link_to "Sign In", new_user_session_path  %></li>
	<li><%= link_to "Sign Up", new_user_registration_path  %></li>
	<% end %>
    </ul>
    
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DEKO-TAUSCH</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |name ,msg| %>
    <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == "notice" ? "success" : "danger" %> alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
    <% end %>
    <% end %>

     <%= yield %>

    <%= render 'layouts/footer' %>
  </div>
</body>
</html>

app/views/page/about.html.erb
<h1>Page#about</h1>
<p>Find me in app/views/page/about.html.erb</p>

app/views/page/contact.html.erb
<h1>Page#contact</h1>
<p>Find me in app/views/page/contact.html.erb</p>